openapi: 3.0.3
info:
  title: Platform Func
  description: |-
    Platform Func
  termsOfService: https://example.com
  contact:
    email: morning.night.guild@example.com
  license:
    name: MIT
  version: 0.0.1
servers:
  - url: https://localhost:9090
tags:
  - name: health
    description: ヘルスチェック
  - name: article
    description: 記事
paths:
  /v1/health:
    get:
      tags:
        - health
      summary: ヘルスチェック
      description: ヘルスチェック
      operationId: v1Health
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /v1/article:
    post:
      tags:
        - article
      summary: ブログ取得
      description: ブログ取得
      operationId: v1ScrapingBlog
      security:
        - apiKey: []      
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: api-key
      in: header
