name: deploy
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yaml
      - "**/**.go"
      - go.mod
      - go.sum
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install vercel cli
        run: npm install --global vercel@latest
      - name: Setup
        run: |
          mkdir .vercel
          echo '{"orgId":"${{ secrets.VERCEL_ORG_ID }}","projectId":"${{ secrets.VERCEL_PROJECT_ID }}"}' > .vercel/project.json
      - name: Deploy vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
